TOP=../..
include $(TOP)/configure/CONFIG

DB += fzoomVx.db
DB += $(ASYN)/db/asynRecord.db
#DB += BL06I-MO-IOC-01_sim.db

#USES_TEMPLATE += $(MOTOR)/db/motor.template
#USES_TEMPLATE += $(MOTOR)/db/basic_motor.template

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
